name: 'Better Tree Generator'
description: 'Generate a directory structure tree and update the README.md file in the repository.'
author: 'MRfantastic3DGamer'
branding:
  color: 'blue'
  icon: 'code'

inputs:
  path:
    description: 'The path of the directory to generate the tree from.'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
      shell: bash

    - name: Build the project
      run: cargo build --release
      shell: bash

    - name: Generate the tree structure
      run: |
        target/release/better-tree ${{ inputs.path }} > output.txt
      shell: bash

    - name: Update README.md
      run: |
        if grep -q '<!---BETTER_FILES_TREE-->' README.md; then
          sed -i '/<!---BETTER_FILES_TREE-->/!b;n;c\```text\n' output.txt README.md
          sed -i '/<!---BETTER_FILES_TREE-->/!b;n;c\```text\n$(cat output.txt)' README.md
        else
          echo '<!---BETTER_FILES_TREE-->\n```text\n$(cat output.txt)\n```' >> README.md
        fi
      shell: bash

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Updated directory structure in README.md"
        git push
      shell: bash
