name: Build and Push Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Release Executable
        run: cargo build --release

      - name: List Release Directory Contents (Debug Step)
        run: ls -al ./target/release/

      - name: Create Executables Directory
        run: mkdir -p ./executables

      - name: Copy Executable to Directory
        run: cp ./target/release/better-tree ./executables/

      - name: Commit and Push Executable
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./executables/
          git commit -m "[bot]Add built executable"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
