name: Build and Push Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Release Executable
        run: cargo build --release

      - name: Create Executables Directory
        run: mkdir -p ./executables

      - name: debug
        run: tree

      - name: Copy Executable to Directory
        run: cp ./target/release/better-tree ./executables/

      - name: Commit and Push Executable
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          directory: ./executables/
      - name: Test Run
        run: |
          touch TestRun.md
          echo <!---BETTER_FILES_TREE-->``` ``` >> TestRun.md
          ./executables/better-tree -- ./ ./TestRun.md
          cat TestRun.md
